services:
    postgres:
        image: postgres:9.6
        volumes:
        	- ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
        	- "5433:5432"
        environment:
        	- POSTGRES_PASSWORD=postgres
        	- POSTGRES_USER=postgres
    wildfly:
        build: .
        ports:
            - "88:8080"